### PR TITLE
Migrate to Elm 0.17

### PR DESCRIPTION
**Pull request by zaidan**
Works fine with Elm 0.17.1.

### CODE REVIEW

**Comment by Chadtech** [comment]
Wow! Crazy! I decided I was going to make this exact PR a few hours ago, then I refreshed this page to see that you had made this PR. What are the odds of that?

**Comment by zaidan** [comment]
Yeah that's really crazy :D. I have this package as dependency of an important project. Could not wait anymore. I am wondering how many people are waiting for this release.

**Comment by bakkemo** [comment]
thanks for the 0.17 pull request

**Comment by zaidan** [comment]
thanks for merging

**Pull request merged**
